// backend/src/permissions/permission.constants.ts
import { Role } from '../common/enums/role.enum';

export const PERMISSIONS = {
  DASHBOARD_VIEW: 'dashboard.view',

  MAPS_VIEW: 'maps.view',

  TRANSPORTATION_REQUESTS_CREATE: 'transportation_requests.create',
  TRANSPORTATION_REQUESTS_VIEW_OWN: 'transportation_requests.view_own',
  TRANSPORTATION_REQUESTS_VIEW_ALL: 'transportation_requests.view_all',
  TRANSPORTATION_REQUESTS_EDIT_OWN: 'transportation_requests.edit_own',
  TRANSPORTATION_REQUESTS_APPROVE: 'transportation_requests.approve',
  TRANSPORTATION_REQUESTS_REJECT: 'transportation_requests.reject',
  TRANSPORTATION_REQUESTS_CANCEL_OWN: 'transportation_requests.cancel_own',
  TRANSPORTATION_REQUESTS_CANCEL_ANY: 'transportation_requests.cancel_any',
  TRANSPORTATION_REQUESTS_DISPATCH: 'transportation_requests.dispatch',
  TRANSPORTATION_REQUESTS_ASSIGN: 'transportation_requests.assign',
  TRANSPORTATION_REQUESTS_MONITOR: 'transportation_requests.monitor',
  TRANSPORTATION_REQUESTS_COMPLETE: 'transportation_requests.complete',
  TRANSPORTATION_REQUESTS_MANAGE: 'transportation_requests.manage',

  CATALOG_VIEW: 'catalog.view',
  CATALOG_CREATE: 'catalog.create',
  CATALOG_EDIT: 'catalog.edit',

  DRIVER_VIEW: 'driver.view',
  DRIVER_CREATE: 'driver.create',
  DRIVER_EDIT: 'driver.edit',
  DRIVER_DELETE: 'driver.delete',

  CAR_VIEW: 'car.view',
  CAR_CREATE: 'car.create',
  CAR_EDIT: 'car.edit',
  CAR_DELETE: 'car.delete',

  TEST_ACCOUNTS_VIEW: 'test_accounts.view',
  TEST_ACCOUNTS_CREATE: 'test_accounts.create',
  TEST_ACCOUNTS_EDIT: 'test_accounts.edit',
  TEST_ACCOUNTS_DEACTIVATE: 'test_accounts.deactivate',
  TEST_ACCOUNTS_IMPORT: 'test_accounts.import',
  TEST_ACCOUNTS_EXPORT: 'test_accounts.export',
  TEST_ACCOUNTS_DELETE: 'test_accounts.delete',
  TEST_ACCOUNTS_STRESS_TAG: 'test_accounts.stress_tag',

  QA_TESTING_VIEW: 'qa_testing.view',
  QA_TESTING_PROCESSING_CENTER_VIEW: 'qa_testing.processing_center_view',
  PROCESSING_CENTER_BILL_RECORD_CHECKER_VIEW:
    'processing_center.bill_record_checker.view',
  PROCESSING_CENTER_QA_TESTING_PROCESSOR_VIEW:
    'processing_center.qa_testing_processor.view',
  PROCESSING_CENTER_DAILY_REPORT_PROCESSOR_VIEW:
    'processing_center.daily_report_processor.view',
  PROCESSING_CENTER_OSM_METER_PROCESSOR_VIEW:
    'processing_center.osm_meter_processor.view',
  QA_TESTING_AVAILABLE_ARCHIVES_VIEW: 'qa_testing.available_archives_view',
  QA_TESTING_REFRESH: 'qa_testing.refresh',
  QA_TESTING_QUEUE_START: 'qa_testing.queue_start',
  QA_TESTING_RUN_CONTROL: 'qa_testing.run_control',
  QA_TESTING_OPEN_REPORTING: 'qa_testing.open_reporting',
  QA_TESTING_STRESS_TAG: 'qa_testing.stress_tag',
  QA_TESTING_STRESS_UNTAG: 'qa_testing.stress_untag',
  QA_TESTING_UNAPPROVED_TAG_VIEW: 'qa_testing.unapproved_tag.view',
  QA_TESTING_UNAPPROVED_TAG: 'qa_testing.unapproved_tag',
  QA_TESTING_UNAPPROVED_UNTAG: 'qa_testing.unapproved_untag',
  QA_TESTING_EXPORT: 'qa_testing.export',
  QA_TESTING_SUBMIT: 'qa_testing.submit',
  QA_TESTING_REPROCESS: 'qa_testing.reprocess',
  QA_TESTING_BULK_PROCESS: 'qa_testing.bulk_process',
  QA_TESTING_DELETE_PROCESSED: 'qa_testing.delete_processed',
  QA_TESTING_PROCESSED_RUNS_VIEW: 'qa_testing.processed_runs_view',

  QA_TESTING_TEST_TRANSACTIONS_VIEW: 'qa_testing.test_transactions.view',
  QA_TESTING_PER_ACCOUNT_TRANSACTIONS_VIEW:
    'qa_testing.per_account_transactions.view',
  QA_TESTING_TRANSACTION_DETAILS_VIEW: 'qa_testing.transaction_details.view',

  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_EDIT: 'users.edit',
  USERS_CHANGE_STATUS: 'users.change_status',
  USERS_RESET_PASSWORD: 'users.reset_password',
  USERS_UNLOCK: 'users.unlock',

  EMPLOYEE_MANAGEMENT_VIEW: 'employee_management.view',
  EMPLOYEE_MANAGEMENT_PRINT: 'employeeManagement.print',
  EMPLOYEE_MANAGEMENT_EXPORT: 'employeeManagement.export',

  AUDIT_LOGS_VIEW: 'audit_logs.view',

  AUTOMATION_MONITOR_VIEW: 'automation_monitor.view',
  AUTOMATION_MONITOR_MANAGE: 'automation_monitor.manage',

  PERMISSIONS_VIEW: 'permissions.view',
  PERMISSIONS_EDIT: 'permissions.edit',

  BILL_RECORDS_VIEW: 'bill_records.view',
  BILL_RECORDS_CREATE: 'bill_records.create',
  BILL_RECORDS_DOWNLOAD: 'bill_records.download',

  BILL_RECORD_DOWNLOADER_VIEW: 'bill_record_downloader.view',
  BILL_RECORD_DOWNLOADER_CREATE: 'bill_record_downloader.create',
  BILL_RECORD_DOWNLOADER_DOWNLOAD: 'bill_record_downloader.download',
  BILL_RECORD_DOWNLOADER_DELETE: 'bill_record_downloader.delete',

  DATA_SOURCE_VIEW: 'data_source.view',
  DATA_SOURCE_RUN: 'data_source.run',
  DATA_SOURCE_DAILY_REPORT_PER_GAME_VIEW:
    'data_source.daily_report_per_game.view',
  DATA_SOURCE_DAILY_REPORT_PER_GAME_UPLOAD:
    'data_source.daily_report_per_game.upload',
  DATA_SOURCE_DAILY_REPORT_PER_GAME_EXPORT:
    'data_source.daily_report_per_game.export',
  DATA_SOURCE_DAILY_REPORT_PER_GAME_DELETE:
    'data_source.daily_report_per_game.delete',
  DATA_SOURCE_DAILY_REPORT_PER_GAME_REPROCESS:
    'data_source.daily_report_per_game.reprocess',

  DAILY_REPORTS_VIEW: 'daily_reports.view',
  DAILY_REPORTS_CREATE: 'daily_reports.create',
  DAILY_REPORTS_DOWNLOAD: 'daily_reports.download',
  DAILY_REPORTS_DELETE: 'daily_reports.delete',
  DAILY_REPORTS_BULK_DOWNLOAD: 'daily_reports.bulk_download',
  DAILY_REPORTS_BULK_DELETE: 'daily_reports.bulk_delete',
  DAILY_REPORTS_PROCESS: 'daily_reports.process',
  DAILY_REPORTS_FINALIZE: 'daily_reports.finalize',
  DAILY_REPORTS_DATA_SOURCE_VIEW: 'daily_reports.data_source_view',
  DAILY_REPORTS_BATCH_UPLOAD: 'daily_reports.batch_upload',
  DAILY_REPORTS_BATCH_PROCESS: 'daily_reports.batch_process',

  MONTHLY_REPORTS_VIEW: 'monthly_reports.view',
  MONTHLY_REPORTS_CREATE: 'monthly_reports.create',
  MONTHLY_REPORTS_UPDATE: 'monthly_reports.update',
  MONTHLY_REPORTS_FINALIZE: 'monthly_reports.finalize',
  MONTHLY_REPORTS_SUBMIT: 'monthly_reports.submit',
  MONTHLY_REPORTS_APPROVE: 'monthly_reports.approve',
  MONTHLY_REPORTS_VOID: 'monthly_reports.void',
  MONTHLY_REPORTS_DELETE: 'monthly_reports.delete',
  MONTHLY_REPORTS_DOWNLOAD: 'monthly_reports.download',
  MONTHLY_REPORTS_GENERATE_PDF: 'monthly_reports.generate_pdf',

  MCA_REPORTS_VIEW: 'mca_reports.view',
  MCA_REPORTS_CREATE: 'mca_reports.create',
  MCA_REPORTS_UPDATE: 'mca_reports.update',
  MCA_REPORTS_GENERATE_PDF: 'mca_reports.generate_pdf',
  MCA_REPORTS_SUBMIT: 'mca_reports.submit',
  MCA_REPORTS_APPROVE: 'mca_reports.approve',
  MCA_REPORTS_VOID: 'mca_reports.void',
  MCA_REPORTS_DOWNLOAD: 'mca_reports.download',

  MAINTENANCE_FORM_VIEW: 'maintenance_form.view',
  MAINTENANCE_FORM_CREATE: 'maintenance_form.create',
  MAINTENANCE_FORM_BUILDER_VIEW: 'maintenance_form_builder.view',
  MAINTENANCE_FORM_BUILDER_MANAGE: 'maintenance_form_builder.manage',
  MAINTENANCE_LOGS_VIEW: 'maintenance_logs.view',
  MAINTENANCE_LOGS_EXPORT: 'maintenance_logs.export',

  OSM_METER_UPLOADS_VIEW: 'osm_meter_uploads.view',
  OSM_METER_UPLOADS_CREATE: 'osm_meter_uploads.create',
  OSM_METER_UPLOADS_DOWNLOAD: 'osm_meter_uploads.download',
  OSM_METER_UPLOADS_DELETE: 'osm_meter_uploads.delete',
  OSM_METER_UPLOADS_BULK_DELETE: 'osm_meter_uploads.bulk_delete',
  OSM_METER_UPLOADS_PROCESS: 'osm_meter_uploads.process',
  OSM_METER_UPLOADS_FINALIZE: 'osm_meter_uploads.finalize',
  OSM_METER_UPLOADS_DATA_SOURCE_VIEW: 'osm_meter_uploads.data_source_view',
  OSM_METER_UPLOADS_BATCH_UPLOAD: 'osm_meter_uploads.batch_upload',
  OSM_METER_UPLOADS_BATCH_PROCESS: 'osm_meter_uploads.batch_process',
  OSM_METER_UPLOADS_BATCH_FINALIZE: 'osm_meter_uploads.batch_finalize',
  OSM_METER_UPLOADS_STOP_PROCESSING: 'osm_meter_uploads.stop_processing',
  OSM_METER_UPLOADS_REPROCESS: 'osm_meter_uploads.reprocess',
  REPORTS_OSM_HUGE_PAYOUT_SUBMIT_APPROVAL:
    'reports.osm_huge_payout.submit_approval',
  REPORTS_OSM_HUGE_PAYOUT_VIEW_SUBMISSION:
    'reports.osm_huge_payout.view_submission',
  REPORTS_OSM_HUGE_PAYOUT_DOWNLOAD: 'reports.osm_huge_payout.download',
  REPORTS_OSM_HUGE_PAYOUT_SUPERSEDE: 'reports.osm_huge_payout.supersede',

  PDF_EXPORTS_VIEW: 'pdf_exports.view',
  PDF_EXPORTS_GENERATE: 'pdf_exports.generate',
  PDF_EXPORTS_DOWNLOAD: 'pdf_exports.download',
  PDF_EXPORTS_VIEW_FILE: 'pdf_exports.view_file',
  PDF_EXPORTS_REGENERATE: 'pdf_exports.regenerate',
  PDF_EXPORTS_ARCHIVE: 'pdf_exports.archive',

  SIGNATURE_VIEW_SELF: 'signature.view_self',
  SIGNATURE_UPLOAD_SELF: 'signature.upload_self',
  SIGNATURE_REPLACE_SELF: 'signature.replace_self',
  SIGNATURE_REVOKE_SELF: 'signature.revoke_self',

  APPROVAL_VIEW: 'approval.view',
  APPROVAL_SUBMIT: 'approval.submit',
  APPROVAL_APPROVE: 'approval.approve',
  APPROVAL_REJECT: 'approval.reject',
  APPROVAL_EXPORT_SIGNED_PDF: 'approval.export_signed_pdf',
  APPROVAL_DELETE: 'approval.delete',
  PDF_SIGNATURE_RENDER: 'pdf.signature_render',

  NOTIFICATION_VIEW_SELF: 'notification.view_self',
  NOTIFICATION_MARK_READ_SELF: 'notification.mark_read_self',

  QAT_SUBMISSION_VIEW: 'qat_submission.view',
  QAT_SUBMISSION_DOWNLOAD: 'qat_submission.download',
  QAT_SUBMISSION_MERGE: 'qat_submission.merge',
  QAT_SUBMISSION_SUPERSEDE: 'qat_submission.supersede',

  PAGCOR_FORMS_EGLD_VIEW: 'pagcor_forms.egld.view',
  PAGCOR_FORMS_EGLD_CREATE: 'pagcor_forms.egld.create',
  PAGCOR_FORMS_EGLD_DOWNLOAD: 'pagcor_forms.egld.download',
  PAGCOR_FORMS_EGLD_APPROVAL_UPLOAD: 'pagcor_forms.egld.approval_upload',
  PAGCOR_FORMS_EGLD_DELETE: 'pagcor_forms.egld.delete',
  PAGCOR_FORMS_GLDD_VIEW: 'pagcor_forms.gldd.view',
  PAGCOR_FORMS_GLDD_CREATE: 'pagcor_forms.gldd.create',
  PAGCOR_FORMS_GLDD_DOWNLOAD: 'pagcor_forms.gldd.download',
  PAGCOR_FORMS_GLDD_APPROVAL_UPLOAD: 'pagcor_forms.gldd.approval_upload',
  PAGCOR_FORMS_GLDD_DELETE: 'pagcor_forms.gldd.delete',
  PAGCOR_FORMS_CMED_VIEW: 'pagcor_forms.cmed.view',
  PAGCOR_FORMS_CMED_CREATE: 'pagcor_forms.cmed.create',
  PAGCOR_FORMS_CMED_DOWNLOAD: 'pagcor_forms.cmed.download',
  PAGCOR_FORMS_CMED_APPROVAL_UPLOAD: 'pagcor_forms.cmed.approval_upload',
  PAGCOR_FORMS_CMED_DELETE: 'pagcor_forms.cmed.delete',
  PAGCOR_FORMS_ITD_VIEW: 'pagcor_forms.itd.view',
  PAGCOR_FORMS_ITD_CREATE: 'pagcor_forms.itd.create',
  PAGCOR_FORMS_ITD_DOWNLOAD: 'pagcor_forms.itd.download',
  PAGCOR_FORMS_ITD_APPROVAL_UPLOAD: 'pagcor_forms.itd.approval_upload',
  PAGCOR_FORMS_ITD_DELETE: 'pagcor_forms.itd.delete',
  PAGCOR_FORMS_MONITORING_READONLY: 'pagcor_forms.monitoring.readonly',
  PAGCOR_FORMS_MONITORING_DOWNLOAD: 'pagcor_forms.monitoring.download',
  PAGCOR_FORMS_MONITORING_UPDATE: 'pagcor_forms.monitoring.update',
  PAGCOR_FORMS_PUBLIC_INTAKE_ACCEPT: 'pagcor_forms.public_intake.accept',

  LCFRR_VIEW: 'processing_center.lcfrr.view',
  LCFRR_MANAGE: 'processing_center.lcfrr.manage',

  MEGAXCESS_FORMS_EF02_VIEW: 'megaxcess_forms.ef02.view',
  MEGAXCESS_FORMS_EF02_CREATE: 'megaxcess_forms.ef02.create',
  MEGAXCESS_FORMS_EF02_DOWNLOAD: 'megaxcess_forms.ef02.download',
  MEGAXCESS_FORMS_EF02_DELETE: 'megaxcess_forms.ef02.delete',
  MEGAXCESS_FORMS_EF02_APPROVE: 'megaxcess_forms.ef02.approve',
  MEGAXCESS_FORMS_MONITORING_READONLY: 'megaxcess_forms.monitoring.readonly',

  CALENDAR_VIEW: 'calendar.view',
  CALENDAR_CREATE: 'calendar.create',
  CALENDAR_EDIT: 'calendar.edit',
  CALENDAR_DELETE: 'calendar.delete',

  PROJECT_MANAGEMENT_VIEW: 'project_management.view',
  PROJECT_MANAGEMENT_CREATE: 'project_management.create',
  PROJECT_MANAGEMENT_EDIT: 'project_management.edit',
  PROJECT_MANAGEMENT_DELETE: 'project_management.delete',
  PROJECT_MANAGEMENT_ACTIVITY: 'project_management.activity_append',
  PROJECT_MANAGEMENT_DASHBOARD: 'project_management.dashboard',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<Role, PermissionKey[]> = {
  [Role.SUPERADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.MAPS_VIEW,

    PERMISSIONS.TRANSPORTATION_REQUESTS_CREATE,
    PERMISSIONS.TRANSPORTATION_REQUESTS_VIEW_OWN,
    PERMISSIONS.TRANSPORTATION_REQUESTS_VIEW_ALL,
    PERMISSIONS.TRANSPORTATION_REQUESTS_EDIT_OWN,
    PERMISSIONS.TRANSPORTATION_REQUESTS_APPROVE,
    PERMISSIONS.TRANSPORTATION_REQUESTS_REJECT,
    PERMISSIONS.TRANSPORTATION_REQUESTS_CANCEL_OWN,
    PERMISSIONS.TRANSPORTATION_REQUESTS_CANCEL_ANY,
    PERMISSIONS.TRANSPORTATION_REQUESTS_DISPATCH,
    PERMISSIONS.TRANSPORTATION_REQUESTS_ASSIGN,
    PERMISSIONS.TRANSPORTATION_REQUESTS_MONITOR,
    PERMISSIONS.TRANSPORTATION_REQUESTS_COMPLETE,
    PERMISSIONS.TRANSPORTATION_REQUESTS_MANAGE,

    PERMISSIONS.CATALOG_VIEW,
    PERMISSIONS.CATALOG_CREATE,
    PERMISSIONS.CATALOG_EDIT,

    PERMISSIONS.DRIVER_VIEW,
    PERMISSIONS.DRIVER_CREATE,
    PERMISSIONS.DRIVER_EDIT,
    PERMISSIONS.DRIVER_DELETE,

    PERMISSIONS.CAR_VIEW,
    PERMISSIONS.CAR_CREATE,
    PERMISSIONS.CAR_EDIT,
    PERMISSIONS.CAR_DELETE,

    PERMISSIONS.TEST_ACCOUNTS_VIEW,
    PERMISSIONS.TEST_ACCOUNTS_CREATE,
    PERMISSIONS.TEST_ACCOUNTS_EDIT,
    PERMISSIONS.TEST_ACCOUNTS_DEACTIVATE,
    PERMISSIONS.TEST_ACCOUNTS_IMPORT,
    PERMISSIONS.TEST_ACCOUNTS_EXPORT,
    PERMISSIONS.TEST_ACCOUNTS_DELETE,
    PERMISSIONS.TEST_ACCOUNTS_STRESS_TAG,

    PERMISSIONS.QA_TESTING_VIEW,
    PERMISSIONS.QA_TESTING_PROCESSING_CENTER_VIEW,
    PERMISSIONS.PROCESSING_CENTER_BILL_RECORD_CHECKER_VIEW,
    PERMISSIONS.PROCESSING_CENTER_QA_TESTING_PROCESSOR_VIEW,
    PERMISSIONS.PROCESSING_CENTER_DAILY_REPORT_PROCESSOR_VIEW,
    PERMISSIONS.PROCESSING_CENTER_OSM_METER_PROCESSOR_VIEW,
    PERMISSIONS.QA_TESTING_AVAILABLE_ARCHIVES_VIEW,
    PERMISSIONS.QA_TESTING_REFRESH,
    PERMISSIONS.QA_TESTING_QUEUE_START,
    PERMISSIONS.QA_TESTING_RUN_CONTROL,
    PERMISSIONS.QA_TESTING_OPEN_REPORTING,
    PERMISSIONS.QA_TESTING_STRESS_TAG,
    PERMISSIONS.QA_TESTING_STRESS_UNTAG,
    PERMISSIONS.QA_TESTING_UNAPPROVED_TAG_VIEW,
    PERMISSIONS.QA_TESTING_UNAPPROVED_TAG,
    PERMISSIONS.QA_TESTING_UNAPPROVED_UNTAG,
    PERMISSIONS.QA_TESTING_EXPORT,
    PERMISSIONS.QA_TESTING_SUBMIT,
    PERMISSIONS.QA_TESTING_REPROCESS,
    PERMISSIONS.QA_TESTING_BULK_PROCESS,
    PERMISSIONS.QA_TESTING_DELETE_PROCESSED,
    PERMISSIONS.QA_TESTING_PROCESSED_RUNS_VIEW,
    PERMISSIONS.QA_TESTING_TEST_TRANSACTIONS_VIEW,
    PERMISSIONS.QA_TESTING_PER_ACCOUNT_TRANSACTIONS_VIEW,
    PERMISSIONS.QA_TESTING_TRANSACTION_DETAILS_VIEW,

    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_CHANGE_STATUS,
    PERMISSIONS.USERS_RESET_PASSWORD,
    PERMISSIONS.USERS_UNLOCK,
    PERMISSIONS.EMPLOYEE_MANAGEMENT_VIEW,
    PERMISSIONS.EMPLOYEE_MANAGEMENT_PRINT,
    PERMISSIONS.EMPLOYEE_MANAGEMENT_EXPORT,

    PERMISSIONS.AUDIT_LOGS_VIEW,
    PERMISSIONS.AUTOMATION_MONITOR_VIEW,
    PERMISSIONS.AUTOMATION_MONITOR_MANAGE,

    PERMISSIONS.PERMISSIONS_VIEW,
    PERMISSIONS.PERMISSIONS_EDIT,

    PERMISSIONS.BILL_RECORDS_VIEW,
    PERMISSIONS.BILL_RECORDS_CREATE,
    PERMISSIONS.BILL_RECORDS_DOWNLOAD,
    PERMISSIONS.BILL_RECORD_DOWNLOADER_VIEW,
    PERMISSIONS.BILL_RECORD_DOWNLOADER_CREATE,
    PERMISSIONS.BILL_RECORD_DOWNLOADER_DOWNLOAD,
    PERMISSIONS.BILL_RECORD_DOWNLOADER_DELETE,
    PERMISSIONS.DATA_SOURCE_VIEW,
    PERMISSIONS.DATA_SOURCE_RUN,
    PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_VIEW,
    PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_UPLOAD,
    PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_EXPORT,
    PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_DELETE,
    PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_REPROCESS,

    PERMISSIONS.DAILY_REPORTS_VIEW,
    PERMISSIONS.DAILY_REPORTS_CREATE,
    PERMISSIONS.DAILY_REPORTS_DOWNLOAD,
    PERMISSIONS.DAILY_REPORTS_DELETE,
    PERMISSIONS.DAILY_REPORTS_BULK_DOWNLOAD,
    PERMISSIONS.DAILY_REPORTS_BULK_DELETE,
    PERMISSIONS.DAILY_REPORTS_PROCESS,
    PERMISSIONS.DAILY_REPORTS_FINALIZE,
    PERMISSIONS.DAILY_REPORTS_DATA_SOURCE_VIEW,
    PERMISSIONS.DAILY_REPORTS_BATCH_UPLOAD,
    PERMISSIONS.DAILY_REPORTS_BATCH_PROCESS,
    PERMISSIONS.MONTHLY_REPORTS_VIEW,
    PERMISSIONS.MONTHLY_REPORTS_CREATE,
    PERMISSIONS.MONTHLY_REPORTS_UPDATE,
    PERMISSIONS.MONTHLY_REPORTS_FINALIZE,
    PERMISSIONS.MONTHLY_REPORTS_SUBMIT,
    PERMISSIONS.MONTHLY_REPORTS_APPROVE,
    PERMISSIONS.MONTHLY_REPORTS_VOID,
    PERMISSIONS.MONTHLY_REPORTS_DELETE,
    PERMISSIONS.MONTHLY_REPORTS_DOWNLOAD,
    PERMISSIONS.MONTHLY_REPORTS_GENERATE_PDF,
    PERMISSIONS.MCA_REPORTS_VIEW,
    PERMISSIONS.MCA_REPORTS_CREATE,
    PERMISSIONS.MCA_REPORTS_UPDATE,
    PERMISSIONS.MCA_REPORTS_GENERATE_PDF,
    PERMISSIONS.MCA_REPORTS_SUBMIT,
    PERMISSIONS.MCA_REPORTS_APPROVE,
    PERMISSIONS.MCA_REPORTS_VOID,
    PERMISSIONS.MCA_REPORTS_DOWNLOAD,
    PERMISSIONS.MAINTENANCE_FORM_VIEW,
    PERMISSIONS.MAINTENANCE_FORM_CREATE,
    PERMISSIONS.MAINTENANCE_FORM_BUILDER_VIEW,
    PERMISSIONS.MAINTENANCE_FORM_BUILDER_MANAGE,
    PERMISSIONS.MAINTENANCE_LOGS_VIEW,
    PERMISSIONS.MAINTENANCE_LOGS_EXPORT,

    PERMISSIONS.OSM_METER_UPLOADS_VIEW,
    PERMISSIONS.OSM_METER_UPLOADS_CREATE,
    PERMISSIONS.OSM_METER_UPLOADS_DOWNLOAD,
    PERMISSIONS.OSM_METER_UPLOADS_DELETE,
    PERMISSIONS.OSM_METER_UPLOADS_BULK_DELETE,
    PERMISSIONS.OSM_METER_UPLOADS_PROCESS,
    PERMISSIONS.OSM_METER_UPLOADS_FINALIZE,
    PERMISSIONS.OSM_METER_UPLOADS_DATA_SOURCE_VIEW,
    PERMISSIONS.OSM_METER_UPLOADS_BATCH_UPLOAD,
    PERMISSIONS.OSM_METER_UPLOADS_BATCH_PROCESS,
    PERMISSIONS.OSM_METER_UPLOADS_BATCH_FINALIZE,
    PERMISSIONS.OSM_METER_UPLOADS_STOP_PROCESSING,
    PERMISSIONS.OSM_METER_UPLOADS_REPROCESS,
    PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_SUBMIT_APPROVAL,
    PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_VIEW_SUBMISSION,
    PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_DOWNLOAD,
    PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_SUPERSEDE,

    PERMISSIONS.PDF_EXPORTS_VIEW,
    PERMISSIONS.PDF_EXPORTS_GENERATE,
    PERMISSIONS.PDF_EXPORTS_DOWNLOAD,
    PERMISSIONS.PDF_EXPORTS_VIEW_FILE,
    PERMISSIONS.PDF_EXPORTS_REGENERATE,
    PERMISSIONS.PDF_EXPORTS_ARCHIVE,

    PERMISSIONS.SIGNATURE_VIEW_SELF,
    PERMISSIONS.SIGNATURE_UPLOAD_SELF,
    PERMISSIONS.SIGNATURE_REPLACE_SELF,
    PERMISSIONS.SIGNATURE_REVOKE_SELF,
    PERMISSIONS.APPROVAL_VIEW,
    PERMISSIONS.APPROVAL_SUBMIT,
    PERMISSIONS.APPROVAL_APPROVE,
    PERMISSIONS.APPROVAL_REJECT,
    PERMISSIONS.APPROVAL_EXPORT_SIGNED_PDF,
    PERMISSIONS.APPROVAL_DELETE,
    PERMISSIONS.PDF_SIGNATURE_RENDER,
    PERMISSIONS.NOTIFICATION_VIEW_SELF,
    PERMISSIONS.NOTIFICATION_MARK_READ_SELF,
    PERMISSIONS.QAT_SUBMISSION_VIEW,
    PERMISSIONS.QAT_SUBMISSION_DOWNLOAD,
    PERMISSIONS.QAT_SUBMISSION_MERGE,
    PERMISSIONS.QAT_SUBMISSION_SUPERSEDE,

    PERMISSIONS.PAGCOR_FORMS_EGLD_VIEW,
    PERMISSIONS.PAGCOR_FORMS_EGLD_CREATE,
    PERMISSIONS.PAGCOR_FORMS_EGLD_DOWNLOAD,
    PERMISSIONS.PAGCOR_FORMS_EGLD_APPROVAL_UPLOAD,
    PERMISSIONS.PAGCOR_FORMS_EGLD_DELETE,
    PERMISSIONS.PAGCOR_FORMS_GLDD_VIEW,
    PERMISSIONS.PAGCOR_FORMS_GLDD_CREATE,
    PERMISSIONS.PAGCOR_FORMS_GLDD_DOWNLOAD,
    PERMISSIONS.PAGCOR_FORMS_GLDD_APPROVAL_UPLOAD,
    PERMISSIONS.PAGCOR_FORMS_GLDD_DELETE,
    PERMISSIONS.PAGCOR_FORMS_CMED_VIEW,
    PERMISSIONS.PAGCOR_FORMS_CMED_CREATE,
    PERMISSIONS.PAGCOR_FORMS_CMED_DOWNLOAD,
    PERMISSIONS.PAGCOR_FORMS_CMED_APPROVAL_UPLOAD,
    PERMISSIONS.PAGCOR_FORMS_CMED_DELETE,
    PERMISSIONS.PAGCOR_FORMS_ITD_VIEW,
    PERMISSIONS.PAGCOR_FORMS_ITD_CREATE,
    PERMISSIONS.PAGCOR_FORMS_ITD_DOWNLOAD,
    PERMISSIONS.PAGCOR_FORMS_ITD_APPROVAL_UPLOAD,
    PERMISSIONS.PAGCOR_FORMS_ITD_DELETE,
    PERMISSIONS.PAGCOR_FORMS_MONITORING_READONLY,
    PERMISSIONS.PAGCOR_FORMS_MONITORING_DOWNLOAD,
    PERMISSIONS.PAGCOR_FORMS_MONITORING_UPDATE,
    PERMISSIONS.PAGCOR_FORMS_PUBLIC_INTAKE_ACCEPT,

    PERMISSIONS.LCFRR_VIEW,
    PERMISSIONS.LCFRR_MANAGE,

    PERMISSIONS.MEGAXCESS_FORMS_EF02_VIEW,
    PERMISSIONS.MEGAXCESS_FORMS_EF02_CREATE,
    PERMISSIONS.MEGAXCESS_FORMS_EF02_DOWNLOAD,
    PERMISSIONS.MEGAXCESS_FORMS_EF02_DELETE,
    PERMISSIONS.MEGAXCESS_FORMS_EF02_APPROVE,
    PERMISSIONS.MEGAXCESS_FORMS_MONITORING_READONLY,

    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_CREATE,
    PERMISSIONS.CALENDAR_EDIT,
    PERMISSIONS.CALENDAR_DELETE,

    PERMISSIONS.PROJECT_MANAGEMENT_VIEW,
    PERMISSIONS.PROJECT_MANAGEMENT_CREATE,
    PERMISSIONS.PROJECT_MANAGEMENT_EDIT,
    PERMISSIONS.PROJECT_MANAGEMENT_DELETE,
    PERMISSIONS.PROJECT_MANAGEMENT_ACTIVITY,
    PERMISSIONS.PROJECT_MANAGEMENT_DASHBOARD,
  ],

  [Role.ADMIN]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.MAPS_VIEW,

    PERMISSIONS.TRANSPORTATION_REQUESTS_CREATE,
    PERMISSIONS.TRANSPORTATION_REQUESTS_VIEW_OWN,
    PERMISSIONS.TRANSPORTATION_REQUESTS_VIEW_ALL,
    PERMISSIONS.TRANSPORTATION_REQUESTS_EDIT_OWN,
    PERMISSIONS.TRANSPORTATION_REQUESTS_APPROVE,
    PERMISSIONS.TRANSPORTATION_REQUESTS_REJECT,
    PERMISSIONS.TRANSPORTATION_REQUESTS_CANCEL_OWN,
    PERMISSIONS.TRANSPORTATION_REQUESTS_CANCEL_ANY,
    PERMISSIONS.TRANSPORTATION_REQUESTS_DISPATCH,
    PERMISSIONS.TRANSPORTATION_REQUESTS_ASSIGN,
    PERMISSIONS.TRANSPORTATION_REQUESTS_MONITOR,
    PERMISSIONS.TRANSPORTATION_REQUESTS_COMPLETE,
    PERMISSIONS.TRANSPORTATION_REQUESTS_MANAGE,

    PERMISSIONS.CATALOG_VIEW,
    PERMISSIONS.CATALOG_CREATE,
    PERMISSIONS.CATALOG_EDIT,

    PERMISSIONS.DRIVER_VIEW,
    PERMISSIONS.DRIVER_CREATE,
    PERMISSIONS.DRIVER_EDIT,
    PERMISSIONS.DRIVER_DELETE,

    PERMISSIONS.CAR_VIEW,
    PERMISSIONS.CAR_CREATE,
    PERMISSIONS.CAR_EDIT,
    PERMISSIONS.CAR_DELETE,

    PERMISSIONS.TEST_ACCOUNTS_VIEW,
    PERMISSIONS.TEST_ACCOUNTS_CREATE,
    PERMISSIONS.TEST_ACCOUNTS_EDIT,
    PERMISSIONS.TEST_ACCOUNTS_DEACTIVATE,
    PERMISSIONS.TEST_ACCOUNTS_IMPORT,
    PERMISSIONS.TEST_ACCOUNTS_EXPORT,
    PERMISSIONS.TEST_ACCOUNTS_DELETE,
    PERMISSIONS.TEST_ACCOUNTS_STRESS_TAG,

    PERMISSIONS.QA_TESTING_VIEW,
    PERMISSIONS.QA_TESTING_PROCESSING_CENTER_VIEW,
    PERMISSIONS.PROCESSING_CENTER_BILL_RECORD_CHECKER_VIEW,
    PERMISSIONS.PROCESSING_CENTER_QA_TESTING_PROCESSOR_VIEW,
    PERMISSIONS.PROCESSING_CENTER_DAILY_REPORT_PROCESSOR_VIEW,
    PERMISSIONS.PROCESSING_CENTER_OSM_METER_PROCESSOR_VIEW,
    PERMISSIONS.QA_TESTING_AVAILABLE_ARCHIVES_VIEW,
    PERMISSIONS.QA_TESTING_REFRESH,
    PERMISSIONS.QA_TESTING_QUEUE_START,
    PERMISSIONS.QA_TESTING_RUN_CONTROL,
    PERMISSIONS.QA_TESTING_OPEN_REPORTING,
    PERMISSIONS.QA_TESTING_STRESS_TAG,
    PERMISSIONS.QA_TESTING_STRESS_UNTAG,
    PERMISSIONS.QA_TESTING_UNAPPROVED_TAG_VIEW,
    PERMISSIONS.QA_TESTING_UNAPPROVED_TAG,
    PERMISSIONS.QA_TESTING_UNAPPROVED_UNTAG,
    PERMISSIONS.QA_TESTING_EXPORT,
    PERMISSIONS.QA_TESTING_SUBMIT,
    PERMISSIONS.QA_TESTING_REPROCESS,
    PERMISSIONS.QA_TESTING_BULK_PROCESS,
    PERMISSIONS.QA_TESTING_DELETE_PROCESSED,
    PERMISSIONS.QA_TESTING_PROCESSED_RUNS_VIEW,
    PERMISSIONS.QA_TESTING_TEST_TRANSACTIONS_VIEW,
    PERMISSIONS.QA_TESTING_PER_ACCOUNT_TRANSACTIONS_VIEW,
    PERMISSIONS.QA_TESTING_TRANSACTION_DETAILS_VIEW,

    PERMISSIONS.USERS_VIEW,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_EDIT,
    PERMISSIONS.USERS_CHANGE_STATUS,
    PERMISSIONS.USERS_RESET_PASSWORD,
    PERMISSIONS.USERS_UNLOCK,
    PERMISSIONS.EMPLOYEE_MANAGEMENT_VIEW,
    PERMISSIONS.EMPLOYEE_MANAGEMENT_PRINT,
    PERMISSIONS.EMPLOYEE_MANAGEMENT_EXPORT,

    PERMISSIONS.AUDIT_LOGS_VIEW,
    PERMISSIONS.AUTOMATION_MONITOR_VIEW,
    PERMISSIONS.AUTOMATION_MONITOR_MANAGE,

    PERMISSIONS.PERMISSIONS_VIEW,

    PERMISSIONS.BILL_RECORDS_VIEW,
    PERMISSIONS.BILL_RECORDS_CREATE,
    PERMISSIONS.BILL_RECORDS_DOWNLOAD,
    PERMISSIONS.BILL_RECORD_DOWNLOADER_VIEW,
    PERMISSIONS.BILL_RECORD_DOWNLOADER_CREATE,
    PERMISSIONS.BILL_RECORD_DOWNLOADER_DOWNLOAD,
    PERMISSIONS.BILL_RECORD_DOWNLOADER_DELETE,
    PERMISSIONS.DATA_SOURCE_VIEW,
    PERMISSIONS.DATA_SOURCE_RUN,
    PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_VIEW,
    PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_UPLOAD,
    PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_EXPORT,
    PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_DELETE,
    PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_REPROCESS,

    PERMISSIONS.DAILY_REPORTS_VIEW,
    PERMISSIONS.DAILY_REPORTS_CREATE,
    PERMISSIONS.DAILY_REPORTS_DOWNLOAD,
    PERMISSIONS.DAILY_REPORTS_DELETE,
    PERMISSIONS.DAILY_REPORTS_PROCESS,
    PERMISSIONS.DAILY_REPORTS_FINALIZE,
    PERMISSIONS.DAILY_REPORTS_DATA_SOURCE_VIEW,
    PERMISSIONS.DAILY_REPORTS_BATCH_UPLOAD,
    PERMISSIONS.DAILY_REPORTS_BATCH_PROCESS,
    PERMISSIONS.MONTHLY_REPORTS_VIEW,
    PERMISSIONS.MONTHLY_REPORTS_CREATE,
    PERMISSIONS.MONTHLY_REPORTS_UPDATE,
    PERMISSIONS.MONTHLY_REPORTS_FINALIZE,
    PERMISSIONS.MONTHLY_REPORTS_SUBMIT,
    PERMISSIONS.MONTHLY_REPORTS_APPROVE,
    PERMISSIONS.MONTHLY_REPORTS_VOID,
    PERMISSIONS.MONTHLY_REPORTS_DELETE,
    PERMISSIONS.MONTHLY_REPORTS_DOWNLOAD,
    PERMISSIONS.MONTHLY_REPORTS_GENERATE_PDF,
    PERMISSIONS.MCA_REPORTS_VIEW,
    PERMISSIONS.MCA_REPORTS_CREATE,
    PERMISSIONS.MCA_REPORTS_UPDATE,
    PERMISSIONS.MCA_REPORTS_GENERATE_PDF,
    PERMISSIONS.MCA_REPORTS_SUBMIT,
    PERMISSIONS.MCA_REPORTS_APPROVE,
    PERMISSIONS.MCA_REPORTS_VOID,
    PERMISSIONS.MCA_REPORTS_DOWNLOAD,
    PERMISSIONS.MAINTENANCE_FORM_VIEW,
    PERMISSIONS.MAINTENANCE_FORM_CREATE,
    PERMISSIONS.MAINTENANCE_FORM_BUILDER_VIEW,
    PERMISSIONS.MAINTENANCE_FORM_BUILDER_MANAGE,
    PERMISSIONS.MAINTENANCE_LOGS_VIEW,
    PERMISSIONS.MAINTENANCE_LOGS_EXPORT,

    PERMISSIONS.OSM_METER_UPLOADS_VIEW,
    PERMISSIONS.OSM_METER_UPLOADS_CREATE,
    PERMISSIONS.OSM_METER_UPLOADS_DOWNLOAD,
    PERMISSIONS.OSM_METER_UPLOADS_DELETE,
    PERMISSIONS.OSM_METER_UPLOADS_BULK_DELETE,
    PERMISSIONS.OSM_METER_UPLOADS_PROCESS,
    PERMISSIONS.OSM_METER_UPLOADS_FINALIZE,
    PERMISSIONS.OSM_METER_UPLOADS_DATA_SOURCE_VIEW,
    PERMISSIONS.OSM_METER_UPLOADS_BATCH_UPLOAD,
    PERMISSIONS.OSM_METER_UPLOADS_BATCH_PROCESS,
    PERMISSIONS.OSM_METER_UPLOADS_BATCH_FINALIZE,
    PERMISSIONS.OSM_METER_UPLOADS_STOP_PROCESSING,
    PERMISSIONS.OSM_METER_UPLOADS_REPROCESS,
    PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_SUBMIT_APPROVAL,
    PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_VIEW_SUBMISSION,
    PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_DOWNLOAD,
    PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_SUPERSEDE,

    PERMISSIONS.PDF_EXPORTS_VIEW,
    PERMISSIONS.PDF_EXPORTS_GENERATE,
    PERMISSIONS.PDF_EXPORTS_DOWNLOAD,
    PERMISSIONS.PDF_EXPORTS_VIEW_FILE,
    PERMISSIONS.PDF_EXPORTS_REGENERATE,

    PERMISSIONS.SIGNATURE_VIEW_SELF,
    PERMISSIONS.SIGNATURE_UPLOAD_SELF,
    PERMISSIONS.SIGNATURE_REPLACE_SELF,
    PERMISSIONS.SIGNATURE_REVOKE_SELF,
    PERMISSIONS.APPROVAL_VIEW,
    PERMISSIONS.APPROVAL_SUBMIT,
    PERMISSIONS.APPROVAL_APPROVE,
    PERMISSIONS.APPROVAL_REJECT,
    PERMISSIONS.APPROVAL_EXPORT_SIGNED_PDF,
    PERMISSIONS.PDF_SIGNATURE_RENDER,
    PERMISSIONS.NOTIFICATION_VIEW_SELF,
    PERMISSIONS.NOTIFICATION_MARK_READ_SELF,
    PERMISSIONS.QAT_SUBMISSION_VIEW,
    PERMISSIONS.QAT_SUBMISSION_DOWNLOAD,
    PERMISSIONS.QAT_SUBMISSION_MERGE,
    PERMISSIONS.QAT_SUBMISSION_SUPERSEDE,

    PERMISSIONS.PAGCOR_FORMS_EGLD_VIEW,
    PERMISSIONS.PAGCOR_FORMS_EGLD_CREATE,
    PERMISSIONS.PAGCOR_FORMS_EGLD_DOWNLOAD,
    PERMISSIONS.PAGCOR_FORMS_EGLD_APPROVAL_UPLOAD,
    PERMISSIONS.PAGCOR_FORMS_GLDD_VIEW,
    PERMISSIONS.PAGCOR_FORMS_GLDD_CREATE,
    PERMISSIONS.PAGCOR_FORMS_GLDD_DOWNLOAD,
    PERMISSIONS.PAGCOR_FORMS_GLDD_APPROVAL_UPLOAD,
    PERMISSIONS.PAGCOR_FORMS_CMED_VIEW,
    PERMISSIONS.PAGCOR_FORMS_CMED_CREATE,
    PERMISSIONS.PAGCOR_FORMS_CMED_DOWNLOAD,
    PERMISSIONS.PAGCOR_FORMS_CMED_APPROVAL_UPLOAD,
    PERMISSIONS.PAGCOR_FORMS_ITD_VIEW,
    PERMISSIONS.PAGCOR_FORMS_ITD_CREATE,
    PERMISSIONS.PAGCOR_FORMS_ITD_DOWNLOAD,
    PERMISSIONS.PAGCOR_FORMS_ITD_APPROVAL_UPLOAD,
    PERMISSIONS.PAGCOR_FORMS_MONITORING_READONLY,
    PERMISSIONS.PAGCOR_FORMS_MONITORING_DOWNLOAD,
    PERMISSIONS.PAGCOR_FORMS_MONITORING_UPDATE,
    PERMISSIONS.PAGCOR_FORMS_PUBLIC_INTAKE_ACCEPT,

    PERMISSIONS.LCFRR_VIEW,
    PERMISSIONS.LCFRR_MANAGE,

    PERMISSIONS.MEGAXCESS_FORMS_EF02_VIEW,
    PERMISSIONS.MEGAXCESS_FORMS_EF02_CREATE,
    PERMISSIONS.MEGAXCESS_FORMS_EF02_DOWNLOAD,
    PERMISSIONS.MEGAXCESS_FORMS_EF02_DELETE,
    PERMISSIONS.MEGAXCESS_FORMS_EF02_APPROVE,
    PERMISSIONS.MEGAXCESS_FORMS_MONITORING_READONLY,

    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_CREATE,
    PERMISSIONS.CALENDAR_EDIT,
    PERMISSIONS.CALENDAR_DELETE,

    PERMISSIONS.PROJECT_MANAGEMENT_VIEW,
    PERMISSIONS.PROJECT_MANAGEMENT_CREATE,
    PERMISSIONS.PROJECT_MANAGEMENT_EDIT,
    PERMISSIONS.PROJECT_MANAGEMENT_ACTIVITY,
    PERMISSIONS.PROJECT_MANAGEMENT_DASHBOARD,
  ],

  [Role.USER]: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.MAPS_VIEW,

    PERMISSIONS.TRANSPORTATION_REQUESTS_CREATE,
    PERMISSIONS.TRANSPORTATION_REQUESTS_VIEW_OWN,

    PERMISSIONS.BILL_RECORDS_VIEW,

    PERMISSIONS.DAILY_REPORTS_VIEW,
    PERMISSIONS.DAILY_REPORTS_CREATE,
    PERMISSIONS.DAILY_REPORTS_DOWNLOAD,
    PERMISSIONS.MONTHLY_REPORTS_VIEW,
    PERMISSIONS.MONTHLY_REPORTS_CREATE,
    PERMISSIONS.MONTHLY_REPORTS_UPDATE,
    PERMISSIONS.MONTHLY_REPORTS_FINALIZE,
    PERMISSIONS.MONTHLY_REPORTS_SUBMIT,
    PERMISSIONS.MONTHLY_REPORTS_VOID,
    PERMISSIONS.MONTHLY_REPORTS_DOWNLOAD,
    PERMISSIONS.MONTHLY_REPORTS_GENERATE_PDF,
    PERMISSIONS.MCA_REPORTS_VIEW,
    PERMISSIONS.MCA_REPORTS_CREATE,
    PERMISSIONS.MCA_REPORTS_UPDATE,
    PERMISSIONS.MCA_REPORTS_GENERATE_PDF,
    PERMISSIONS.MCA_REPORTS_SUBMIT,
    PERMISSIONS.MCA_REPORTS_VOID,
    PERMISSIONS.MCA_REPORTS_DOWNLOAD,

    PERMISSIONS.OSM_METER_UPLOADS_VIEW,
    PERMISSIONS.OSM_METER_UPLOADS_CREATE,
    PERMISSIONS.OSM_METER_UPLOADS_DOWNLOAD,

    PERMISSIONS.QA_TESTING_VIEW,
    PERMISSIONS.QA_TESTING_PROCESSING_CENTER_VIEW,
    PERMISSIONS.PROCESSING_CENTER_BILL_RECORD_CHECKER_VIEW,
    PERMISSIONS.PROCESSING_CENTER_QA_TESTING_PROCESSOR_VIEW,
    PERMISSIONS.PROCESSING_CENTER_DAILY_REPORT_PROCESSOR_VIEW,
    PERMISSIONS.PROCESSING_CENTER_OSM_METER_PROCESSOR_VIEW,
    PERMISSIONS.QA_TESTING_AVAILABLE_ARCHIVES_VIEW,
    PERMISSIONS.QA_TESTING_REFRESH,
    PERMISSIONS.QA_TESTING_OPEN_REPORTING,
    PERMISSIONS.QA_TESTING_UNAPPROVED_TAG_VIEW,
    PERMISSIONS.QA_TESTING_PROCESSED_RUNS_VIEW,
    PERMISSIONS.QA_TESTING_TEST_TRANSACTIONS_VIEW,
    PERMISSIONS.QA_TESTING_PER_ACCOUNT_TRANSACTIONS_VIEW,
    PERMISSIONS.QA_TESTING_TRANSACTION_DETAILS_VIEW,

    PERMISSIONS.SIGNATURE_VIEW_SELF,
    PERMISSIONS.SIGNATURE_UPLOAD_SELF,
    PERMISSIONS.SIGNATURE_REPLACE_SELF,
    PERMISSIONS.SIGNATURE_REVOKE_SELF,
    PERMISSIONS.APPROVAL_VIEW,
    PERMISSIONS.APPROVAL_SUBMIT,
    PERMISSIONS.NOTIFICATION_VIEW_SELF,
    PERMISSIONS.NOTIFICATION_MARK_READ_SELF,
    PERMISSIONS.QAT_SUBMISSION_VIEW,
    PERMISSIONS.QAT_SUBMISSION_DOWNLOAD,
    PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_SUBMIT_APPROVAL,
    PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_VIEW_SUBMISSION,
    PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_DOWNLOAD,

    PERMISSIONS.PAGCOR_FORMS_EGLD_VIEW,
    PERMISSIONS.PAGCOR_FORMS_EGLD_CREATE,
    PERMISSIONS.PAGCOR_FORMS_EGLD_DOWNLOAD,
    PERMISSIONS.PAGCOR_FORMS_GLDD_VIEW,
    PERMISSIONS.PAGCOR_FORMS_GLDD_CREATE,
    PERMISSIONS.PAGCOR_FORMS_GLDD_DOWNLOAD,
    PERMISSIONS.PAGCOR_FORMS_CMED_VIEW,
    PERMISSIONS.PAGCOR_FORMS_CMED_CREATE,
    PERMISSIONS.PAGCOR_FORMS_CMED_DOWNLOAD,
    PERMISSIONS.PAGCOR_FORMS_ITD_VIEW,
    PERMISSIONS.PAGCOR_FORMS_ITD_CREATE,
    PERMISSIONS.PAGCOR_FORMS_ITD_DOWNLOAD,

    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_CREATE,

    PERMISSIONS.PROJECT_MANAGEMENT_VIEW,
    PERMISSIONS.PROJECT_MANAGEMENT_ACTIVITY,
    PERMISSIONS.PROJECT_MANAGEMENT_DASHBOARD,
  ],
};

export const PERMISSION_GROUPS = [
  {
    module: 'Dashboard',
    permissions: [{ key: PERMISSIONS.DASHBOARD_VIEW, label: 'View Dashboard' }],
  },
  {
    module: 'Catalog',
    permissions: [
      { key: PERMISSIONS.CATALOG_VIEW, label: 'View Catalog' },
      { key: PERMISSIONS.CATALOG_CREATE, label: 'Create Catalog' },
      { key: PERMISSIONS.CATALOG_EDIT, label: 'Edit Catalog' },
    ],
  },
  {
    module: 'Drivers',
    permissions: [
      { key: PERMISSIONS.DRIVER_VIEW, label: 'View Drivers' },
      { key: PERMISSIONS.DRIVER_CREATE, label: 'Create Driver' },
      { key: PERMISSIONS.DRIVER_EDIT, label: 'Edit Driver' },
      { key: PERMISSIONS.DRIVER_DELETE, label: 'Delete Driver' },
    ],
  },
  {
    module: 'Cars',
    permissions: [
      { key: PERMISSIONS.CAR_VIEW, label: 'View Cars' },
      { key: PERMISSIONS.CAR_CREATE, label: 'Create Car' },
      { key: PERMISSIONS.CAR_EDIT, label: 'Edit Car' },
      { key: PERMISSIONS.CAR_DELETE, label: 'Delete Car' },
    ],
  },
  {
    module: 'Maps',
    permissions: [{ key: PERMISSIONS.MAPS_VIEW, label: 'View Maps' }],
  },
  {
    module: 'Transportation Requests',
    permissions: [
      {
        key: PERMISSIONS.TRANSPORTATION_REQUESTS_CREATE,
        label: 'Create Requests',
      },
      {
        key: PERMISSIONS.TRANSPORTATION_REQUESTS_VIEW_OWN,
        label: 'View Own Requests',
      },
      {
        key: PERMISSIONS.TRANSPORTATION_REQUESTS_VIEW_ALL,
        label: 'View All Requests',
      },
      {
        key: PERMISSIONS.TRANSPORTATION_REQUESTS_EDIT_OWN,
        label: 'Edit Own Requests',
      },
      {
        key: PERMISSIONS.TRANSPORTATION_REQUESTS_APPROVE,
        label: 'Approve Requests',
      },
      {
        key: PERMISSIONS.TRANSPORTATION_REQUESTS_REJECT,
        label: 'Reject Requests',
      },
      {
        key: PERMISSIONS.TRANSPORTATION_REQUESTS_CANCEL_OWN,
        label: 'Cancel Own Requests',
      },
      {
        key: PERMISSIONS.TRANSPORTATION_REQUESTS_CANCEL_ANY,
        label: 'Cancel Any Request',
      },
      {
        key: PERMISSIONS.TRANSPORTATION_REQUESTS_DISPATCH,
        label: 'Dispatch Requests',
      },
      {
        key: PERMISSIONS.TRANSPORTATION_REQUESTS_ASSIGN,
        label: 'Assign Drivers & Vehicles',
      },
      {
        key: PERMISSIONS.TRANSPORTATION_REQUESTS_MONITOR,
        label: 'Monitor Active Trips',
      },
      {
        key: PERMISSIONS.TRANSPORTATION_REQUESTS_COMPLETE,
        label: 'Complete Requests',
      },
      {
        key: PERMISSIONS.TRANSPORTATION_REQUESTS_MANAGE,
        label: 'Manage All Requests',
      },
    ],
  },
  {
    module: 'Test Accounts',
    permissions: [
      { key: PERMISSIONS.TEST_ACCOUNTS_VIEW, label: 'View Test Accounts' },
      { key: PERMISSIONS.TEST_ACCOUNTS_CREATE, label: 'Create Test Accounts' },
      { key: PERMISSIONS.TEST_ACCOUNTS_EDIT, label: 'Edit Test Accounts' },
      {
        key: PERMISSIONS.TEST_ACCOUNTS_DEACTIVATE,
        label: 'Activate / Deactivate Test Accounts',
      },
      { key: PERMISSIONS.TEST_ACCOUNTS_IMPORT, label: 'Import Test Accounts' },
      { key: PERMISSIONS.TEST_ACCOUNTS_EXPORT, label: 'Export Test Accounts' },
      { key: PERMISSIONS.TEST_ACCOUNTS_DELETE, label: 'Delete Test Accounts' },
      {
        key: PERMISSIONS.TEST_ACCOUNTS_STRESS_TAG,
        label: 'Tag Test Accounts as Stress Test',
      },
    ],
  },
  {
    module: 'Processing Center',
    permissions: [
      {
        key: PERMISSIONS.QA_TESTING_PROCESSING_CENTER_VIEW,
        label: 'View Processing Center',
      },
      {
        key: PERMISSIONS.PROCESSING_CENTER_BILL_RECORD_CHECKER_VIEW,
        label: 'View Bill Record Checker',
      },
      {
        key: PERMISSIONS.PROCESSING_CENTER_QA_TESTING_PROCESSOR_VIEW,
        label: 'View QA Testing Processor',
      },
      {
        key: PERMISSIONS.PROCESSING_CENTER_DAILY_REPORT_PROCESSOR_VIEW,
        label: 'View Daily Report Processor',
      },
      {
        key: PERMISSIONS.PROCESSING_CENTER_OSM_METER_PROCESSOR_VIEW,
        label: 'View OSM Meter Processor',
      },
      {
        key: PERMISSIONS.LCFRR_VIEW,
        label: 'View LCFRR Admin Panel',
      },
      {
        key: PERMISSIONS.LCFRR_MANAGE,
        label: 'Manage LCFRR Categories',
      },
    ],
  },
  {
    module: 'QA Testing Reporting',
    permissions: [
      { key: PERMISSIONS.QA_TESTING_VIEW, label: 'View QA Testing Reporting' },
      {
        key: PERMISSIONS.QA_TESTING_AVAILABLE_ARCHIVES_VIEW,
        label: 'View Available QA Archives',
      },
      {
        key: PERMISSIONS.QA_TESTING_REFRESH,
        label: 'Refresh QA Processor Data',
      },
      { key: PERMISSIONS.QA_TESTING_QUEUE_START, label: 'Start QA Queue' },
      {
        key: PERMISSIONS.QA_TESTING_RUN_CONTROL,
        label: 'Stop / Cancel QA Runs',
      },
      {
        key: PERMISSIONS.QA_TESTING_OPEN_REPORTING,
        label: 'Open QA Testing Reporting',
      },
      {
        key: PERMISSIONS.QA_TESTING_STRESS_TAG,
        label: 'Apply Stress Test Tag',
      },
      {
        key: PERMISSIONS.QA_TESTING_STRESS_UNTAG,
        label: 'Remove Stress Test Tag',
      },
      {
        key: PERMISSIONS.QA_TESTING_UNAPPROVED_TAG_VIEW,
        label: 'View Unapproved Test Account Tags',
      },
      {
        key: PERMISSIONS.QA_TESTING_UNAPPROVED_TAG,
        label: 'Apply Unapproved Test Account Tag',
      },
      {
        key: PERMISSIONS.QA_TESTING_UNAPPROVED_UNTAG,
        label: 'Remove Unapproved Test Account Tag',
      },
      { key: PERMISSIONS.QA_TESTING_EXPORT, label: 'Export QA Testing Report' },
      { key: PERMISSIONS.QA_TESTING_SUBMIT, label: 'Submit QA Testing Report' },
      {
        key: PERMISSIONS.QA_TESTING_REPROCESS,
        label: 'Reprocess QA Runs',
      },
      {
        key: PERMISSIONS.QA_TESTING_BULK_PROCESS,
        label: 'Bulk Process QA Archives',
      },
      {
        key: PERMISSIONS.QA_TESTING_DELETE_PROCESSED,
        label: 'Delete Processed QA Runs',
      },
      {
        key: PERMISSIONS.QA_TESTING_PROCESSED_RUNS_VIEW,
        label: 'View Processed QA Runs',
      },
      {
        key: PERMISSIONS.QA_TESTING_TEST_TRANSACTIONS_VIEW,
        label: 'View Test Transactions Report',
      },
      {
        key: PERMISSIONS.QA_TESTING_PER_ACCOUNT_TRANSACTIONS_VIEW,
        label: 'View Per Test Account Transactions Report',
      },
      {
        key: PERMISSIONS.QA_TESTING_TRANSACTION_DETAILS_VIEW,
        label: 'View Consolidated Transaction Details',
      },
    ],
  },
  {
    module: 'Users',
    permissions: [
      { key: PERMISSIONS.USERS_VIEW, label: 'View Users' },
      { key: PERMISSIONS.USERS_CREATE, label: 'Create Users' },
      { key: PERMISSIONS.USERS_EDIT, label: 'Edit Users' },
      {
        key: PERMISSIONS.USERS_CHANGE_STATUS,
        label: 'Activate / Deactivate Users',
      },
      { key: PERMISSIONS.USERS_RESET_PASSWORD, label: 'Reset Password' },
      { key: PERMISSIONS.USERS_UNLOCK, label: 'Unlock User' },
    ],
  },
  {
    module: 'Employee Management',
    permissions: [
      {
        key: PERMISSIONS.EMPLOYEE_MANAGEMENT_VIEW,
        label: 'View Employee Management',
      },
      {
        key: PERMISSIONS.EMPLOYEE_MANAGEMENT_PRINT,
        label: 'Print Employee Attendance',
      },
      {
        key: PERMISSIONS.EMPLOYEE_MANAGEMENT_EXPORT,
        label: 'Export Employee Attendance',
      },
    ],
  },
  {
    module: 'Audit Logs',
    permissions: [
      { key: PERMISSIONS.AUDIT_LOGS_VIEW, label: 'View Audit Logs' },
    ],
  },
  {
    module: 'Automation Monitor',
    permissions: [
      {
        key: PERMISSIONS.AUTOMATION_MONITOR_VIEW,
        label: 'View Automation Monitor',
      },
      {
        key: PERMISSIONS.AUTOMATION_MONITOR_MANAGE,
        label: 'Manage Automation Monitor Alerts',
      },
    ],
  },
  {
    module: 'Permissions',
    permissions: [
      { key: PERMISSIONS.PERMISSIONS_VIEW, label: 'View Permissions Page' },
      { key: PERMISSIONS.PERMISSIONS_EDIT, label: 'Edit Role Permissions' },
    ],
  },
  {
    module: 'Bill Record Downloader',
    permissions: [
      { key: PERMISSIONS.BILL_RECORDS_VIEW, label: 'View Jobs' },
      { key: PERMISSIONS.BILL_RECORDS_CREATE, label: 'Create Job' },
      { key: PERMISSIONS.BILL_RECORDS_DOWNLOAD, label: 'Download TAR' },
      {
        key: PERMISSIONS.BILL_RECORD_DOWNLOADER_VIEW,
        label: 'View Bill Record Downloader Jobs',
      },
      {
        key: PERMISSIONS.BILL_RECORD_DOWNLOADER_CREATE,
        label: 'Create Bill Record Downloader Jobs',
      },
      {
        key: PERMISSIONS.BILL_RECORD_DOWNLOADER_DOWNLOAD,
        label: 'Download Bill Record Downloader Archives',
      },
      {
        key: PERMISSIONS.BILL_RECORD_DOWNLOADER_DELETE,
        label: 'Delete Bill Record Downloader Jobs',
      },
    ],
  },
  {
    module: 'Data Source',
    permissions: [
      { key: PERMISSIONS.DATA_SOURCE_VIEW, label: 'View Data Source' },
      { key: PERMISSIONS.DATA_SOURCE_RUN, label: 'Run Data Source Process' },
      {
        key: PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_VIEW,
        label: 'View Daily Report Per Game',
      },
      {
        key: PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_UPLOAD,
        label: 'Upload Daily Report Per Game CSV',
      },
      {
        key: PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_EXPORT,
        label: 'Export Daily Report Per Game',
      },
      {
        key: PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_DELETE,
        label: 'Delete Daily Report Per Game Uploads',
      },
      {
        key: PERMISSIONS.DATA_SOURCE_DAILY_REPORT_PER_GAME_REPROCESS,
        label: 'Reprocess Daily Report Per Game Uploads',
      },
    ],
  },
  {
    module: 'Daily Report',
    permissions: [
      { key: PERMISSIONS.DAILY_REPORTS_VIEW, label: 'View Daily Reports' },
      { key: PERMISSIONS.DAILY_REPORTS_CREATE, label: 'Create Daily Reports' },
      {
        key: PERMISSIONS.DAILY_REPORTS_DOWNLOAD,
        label: 'Download Daily Reports',
      },
      { key: PERMISSIONS.DAILY_REPORTS_DELETE, label: 'Delete Daily Reports' },
      {
        key: PERMISSIONS.DAILY_REPORTS_BULK_DOWNLOAD,
        label: 'Bulk Download Daily Reports',
      },
      {
        key: PERMISSIONS.DAILY_REPORTS_BULK_DELETE,
        label: 'Bulk Delete Daily Reports',
      },
      {
        key: PERMISSIONS.DAILY_REPORTS_PROCESS,
        label: 'Process Daily Reports',
      },
      {
        key: PERMISSIONS.DAILY_REPORTS_FINALIZE,
        label: 'Finalize Daily Reports',
      },
      {
        key: PERMISSIONS.DAILY_REPORTS_DATA_SOURCE_VIEW,
        label: 'View Daily Report Data Source',
      },
      {
        key: PERMISSIONS.DAILY_REPORTS_BATCH_UPLOAD,
        label: 'Batch Upload Daily Reports',
      },
      {
        key: PERMISSIONS.DAILY_REPORTS_BATCH_PROCESS,
        label: 'Batch Process Daily Reports',
      },
    ],
  },
  {
    module: 'OSM Meter Uploader',
    permissions: [
      {
        key: PERMISSIONS.OSM_METER_UPLOADS_VIEW,
        label: 'View OSM Meter Uploads',
      },
      {
        key: PERMISSIONS.OSM_METER_UPLOADS_CREATE,
        label: 'Create OSM Meter Uploads',
      },
      {
        key: PERMISSIONS.OSM_METER_UPLOADS_DOWNLOAD,
        label: 'Download OSM Meter Upload Files',
      },
      {
        key: PERMISSIONS.OSM_METER_UPLOADS_DELETE,
        label: 'Delete OSM Meter Uploads',
      },
      {
        key: PERMISSIONS.OSM_METER_UPLOADS_BULK_DELETE,
        label: 'Bulk Delete OSM Meter Uploads',
      },
      {
        key: PERMISSIONS.OSM_METER_UPLOADS_PROCESS,
        label: 'Process OSM Meter Uploads',
      },
      {
        key: PERMISSIONS.OSM_METER_UPLOADS_FINALIZE,
        label: 'Finalize OSM Meter Uploads',
      },
      {
        key: PERMISSIONS.OSM_METER_UPLOADS_DATA_SOURCE_VIEW,
        label: 'View OSM Meter Data Source',
      },
      {
        key: PERMISSIONS.OSM_METER_UPLOADS_BATCH_UPLOAD,
        label: 'Batch Upload OSM Meter Files',
      },
      {
        key: PERMISSIONS.OSM_METER_UPLOADS_BATCH_PROCESS,
        label: 'Batch Process OSM Meter Uploads',
      },
      {
        key: PERMISSIONS.OSM_METER_UPLOADS_BATCH_FINALIZE,
        label: 'Batch Finalize OSM Meter Uploads',
      },
      {
        key: PERMISSIONS.OSM_METER_UPLOADS_STOP_PROCESSING,
        label: 'Stop OSM Meter Processing',
      },
      {
        key: PERMISSIONS.OSM_METER_UPLOADS_REPROCESS,
        label: 'Reprocess OSM Meter Uploads',
      },
      {
        key: PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_SUBMIT_APPROVAL,
        label: 'Submit OSM Huge Payout Monthly Approval',
      },
      {
        key: PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_VIEW_SUBMISSION,
        label: 'View OSM Huge Payout Submissions',
      },
      {
        key: PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_DOWNLOAD,
        label: 'Download OSM Huge Payout Submissions',
      },
      {
        key: PERMISSIONS.REPORTS_OSM_HUGE_PAYOUT_SUPERSEDE,
        label: 'Supersede OSM Huge Payout Submissions',
      },
    ],
  },
  {
    module: 'Monthly Report',
    permissions: [
      {
        key: PERMISSIONS.MONTHLY_REPORTS_VIEW,
        label: 'View Monthly Report Uploads',
      },
      {
        key: PERMISSIONS.MONTHLY_REPORTS_CREATE,
        label: 'Create Monthly Reports',
      },
      {
        key: PERMISSIONS.MONTHLY_REPORTS_UPDATE,
        label: 'Update Monthly Reports',
      },
      {
        key: PERMISSIONS.MONTHLY_REPORTS_FINALIZE,
        label: 'Finalize Monthly Reports',
      },
      {
        key: PERMISSIONS.MONTHLY_REPORTS_SUBMIT,
        label: 'Submit Monthly Reports for Approval',
      },
      {
        key: PERMISSIONS.MONTHLY_REPORTS_APPROVE,
        label: 'Approve Monthly Reports',
      },
      {
        key: PERMISSIONS.MONTHLY_REPORTS_VOID,
        label: 'Void Monthly Reports',
      },
      {
        key: PERMISSIONS.MONTHLY_REPORTS_DELETE,
        label: 'Delete Monthly Reports',
      },
      {
        key: PERMISSIONS.MONTHLY_REPORTS_DOWNLOAD,
        label: 'Download Monthly Report PDFs',
      },
      {
        key: PERMISSIONS.MONTHLY_REPORTS_GENERATE_PDF,
        label: 'Generate Monthly Report PDFs',
      },
    ],
  },
  {
    module: 'MCA Reports',
    permissions: [
      { key: PERMISSIONS.MCA_REPORTS_VIEW, label: 'View MCA Reports' },
      {
        key: PERMISSIONS.MCA_REPORTS_CREATE,
        label: 'Create MCA Report Drafts',
      },
      {
        key: PERMISSIONS.MCA_REPORTS_UPDATE,
        label: 'Update MCA Report Drafts',
      },
      {
        key: PERMISSIONS.MCA_REPORTS_GENERATE_PDF,
        label: 'Generate MCA Report PDFs',
      },
      {
        key: PERMISSIONS.MCA_REPORTS_SUBMIT,
        label: 'Submit MCA Reports for Approval',
      },
      { key: PERMISSIONS.MCA_REPORTS_APPROVE, label: 'Approve MCA Reports' },
      { key: PERMISSIONS.MCA_REPORTS_VOID, label: 'Void MCA Reports' },
      {
        key: PERMISSIONS.MCA_REPORTS_DOWNLOAD,
        label: 'Download MCA Report PDFs',
      },
    ],
  },
  {
    module: 'Maintenance',
    permissions: [
      {
        key: PERMISSIONS.MAINTENANCE_FORM_VIEW,
        label: 'View Maintenance Form',
      },
      {
        key: PERMISSIONS.MAINTENANCE_FORM_CREATE,
        label: 'Submit Maintenance Form',
      },
      {
        key: PERMISSIONS.MAINTENANCE_FORM_BUILDER_VIEW,
        label: 'View Maintenance Form Builder',
      },
      {
        key: PERMISSIONS.MAINTENANCE_FORM_BUILDER_MANAGE,
        label: 'Manage Maintenance Form Builder',
      },
      {
        key: PERMISSIONS.MAINTENANCE_LOGS_VIEW,
        label: 'View Maintenance Logs',
      },
      {
        key: PERMISSIONS.MAINTENANCE_LOGS_EXPORT,
        label: 'Export Maintenance Logs',
      },
    ],
  },
  {
    module: 'PDF Export Records',
    permissions: [
      { key: PERMISSIONS.PDF_EXPORTS_VIEW, label: 'View PDF Export Records' },
      { key: PERMISSIONS.PDF_EXPORTS_GENERATE, label: 'Generate PDF Exports' },
      { key: PERMISSIONS.PDF_EXPORTS_DOWNLOAD, label: 'Download Saved PDFs' },
      { key: PERMISSIONS.PDF_EXPORTS_VIEW_FILE, label: 'View Saved PDFs' },
      {
        key: PERMISSIONS.PDF_EXPORTS_REGENERATE,
        label: 'Regenerate PDF Exports',
      },
      { key: PERMISSIONS.PDF_EXPORTS_ARCHIVE, label: 'Archive PDF Exports' },
    ],
  },
  {
    module: 'Signature Vault',
    permissions: [
      { key: PERMISSIONS.SIGNATURE_VIEW_SELF, label: 'View Own Signature' },
      { key: PERMISSIONS.SIGNATURE_UPLOAD_SELF, label: 'Upload Own Signature' },
      {
        key: PERMISSIONS.SIGNATURE_REPLACE_SELF,
        label: 'Replace Own Signature',
      },
      { key: PERMISSIONS.SIGNATURE_REVOKE_SELF, label: 'Revoke Own Signature' },
    ],
  },
  {
    module: 'Approval Workflow',
    permissions: [
      { key: PERMISSIONS.APPROVAL_VIEW, label: 'View Approvals' },
      { key: PERMISSIONS.APPROVAL_SUBMIT, label: 'Submit Approval Requests' },
      { key: PERMISSIONS.APPROVAL_APPROVE, label: 'Approve Requests' },
      { key: PERMISSIONS.APPROVAL_REJECT, label: 'Reject Requests' },
      {
        key: PERMISSIONS.APPROVAL_EXPORT_SIGNED_PDF,
        label: 'Export Signed PDFs',
      },
      { key: PERMISSIONS.APPROVAL_DELETE, label: 'Delete Approval Requests' },
      {
        key: PERMISSIONS.PDF_SIGNATURE_RENDER,
        label: 'Render PDF Signatures',
      },
    ],
  },
  {
    module: 'Notifications',
    permissions: [
      {
        key: PERMISSIONS.NOTIFICATION_VIEW_SELF,
        label: 'View Own Notifications',
      },
      {
        key: PERMISSIONS.NOTIFICATION_MARK_READ_SELF,
        label: 'Mark Own Notifications Read',
      },
    ],
  },
  {
    module: 'QAT Submission',
    permissions: [
      { key: PERMISSIONS.QAT_SUBMISSION_VIEW, label: 'View QAT Submissions' },
      {
        key: PERMISSIONS.QAT_SUBMISSION_DOWNLOAD,
        label: 'Download QAT Submission PDFs',
      },
      {
        key: PERMISSIONS.QAT_SUBMISSION_MERGE,
        label: 'Merge QAT Submission PDFs',
      },
      {
        key: PERMISSIONS.QAT_SUBMISSION_SUPERSEDE,
        label: 'Supersede QAT Submission PDFs',
      },
    ],
  },
  {
    module: 'PAGCOR Forms',
    permissions: [
      {
        key: PERMISSIONS.PAGCOR_FORMS_EGLD_VIEW,
        label: 'View EGLD Form Submissions',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_EGLD_CREATE,
        label: 'Create / Edit EGLD Form Submissions',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_EGLD_DOWNLOAD,
        label: 'Download EGLD Generated PDFs',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_EGLD_APPROVAL_UPLOAD,
        label: 'Upload / Replace EGLD Approval Document',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_EGLD_DELETE,
        label: 'Delete EGLD Form Submissions',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_GLDD_VIEW,
        label: 'View GLDD Form Submissions',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_GLDD_CREATE,
        label: 'Create / Edit GLDD Form Submissions',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_GLDD_DOWNLOAD,
        label: 'Download GLDD Generated PDFs',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_GLDD_APPROVAL_UPLOAD,
        label: 'Upload / Replace GLDD Approval Document',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_GLDD_DELETE,
        label: 'Delete GLDD Form Submissions',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_CMED_VIEW,
        label: 'View CMED Form Submissions',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_CMED_CREATE,
        label: 'Create / Edit CMED Form Submissions',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_CMED_DOWNLOAD,
        label: 'Download CMED Generated PDFs',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_CMED_APPROVAL_UPLOAD,
        label: 'Upload / Replace CMED Approval Document',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_CMED_DELETE,
        label: 'Delete CMED Form Submissions',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_ITD_VIEW,
        label: 'View ITD Form Submissions',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_ITD_CREATE,
        label: 'Create / Edit ITD Form Submissions',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_ITD_DOWNLOAD,
        label: 'Download ITD Generated PDFs',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_ITD_APPROVAL_UPLOAD,
        label: 'Upload / Replace ITD Approval Document',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_ITD_DELETE,
        label: 'Delete ITD Form Submissions',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_MONITORING_READONLY,
        label: 'View PAGCOR Forms Monitoring',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_MONITORING_DOWNLOAD,
        label: 'Download PAGCOR Forms Monitoring Files',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_MONITORING_UPDATE,
        label: 'Update PAGCOR Forms Monitoring Reference Details',
      },
      {
        key: PERMISSIONS.PAGCOR_FORMS_PUBLIC_INTAKE_ACCEPT,
        label: 'Accept Public PAGCOR Form Intakes',
      },
    ],
  },
  {
    module: 'MegaXcess Forms',
    permissions: [
      {
        key: PERMISSIONS.MEGAXCESS_FORMS_EF02_VIEW,
        label: 'View EF02 Form Submissions',
      },
      {
        key: PERMISSIONS.MEGAXCESS_FORMS_EF02_CREATE,
        label: 'Create / Edit EF02 Form Submissions',
      },
      {
        key: PERMISSIONS.MEGAXCESS_FORMS_EF02_DOWNLOAD,
        label: 'Download EF02 Generated PDFs',
      },
      {
        key: PERMISSIONS.MEGAXCESS_FORMS_EF02_DELETE,
        label: 'Delete EF02 Form Submissions',
      },
      {
        key: PERMISSIONS.MEGAXCESS_FORMS_EF02_APPROVE,
        label: 'Approve / Reject EF02 PDF Approval Requests',
      },
      {
        key: PERMISSIONS.MEGAXCESS_FORMS_MONITORING_READONLY,
        label: 'View MegaXcess Forms Monitoring',
      },
    ],
  },
  {
    module: 'Calendar',
    permissions: [
      { key: PERMISSIONS.CALENDAR_VIEW, label: 'View Calendar' },
      { key: PERMISSIONS.CALENDAR_CREATE, label: 'Create Events' },
      { key: PERMISSIONS.CALENDAR_EDIT, label: 'Edit Events' },
      { key: PERMISSIONS.CALENDAR_DELETE, label: 'Delete Events' },
    ],
  },
  {
    module: 'Project Management',
    permissions: [
      {
        key: PERMISSIONS.PROJECT_MANAGEMENT_VIEW,
        label: 'View Projects, Tasks, Activity Log',
      },
      {
        key: PERMISSIONS.PROJECT_MANAGEMENT_CREATE,
        label: 'Create Projects / Tasks',
      },
      {
        key: PERMISSIONS.PROJECT_MANAGEMENT_EDIT,
        label: 'Edit Projects / Tasks',
      },
      {
        key: PERMISSIONS.PROJECT_MANAGEMENT_DELETE,
        label: 'Delete Projects / Tasks',
      },
      {
        key: PERMISSIONS.PROJECT_MANAGEMENT_ACTIVITY,
        label: 'Append Activity Log Entries',
      },
      {
        key: PERMISSIONS.PROJECT_MANAGEMENT_DASHBOARD,
        label: 'View Command Center Dashboard',
      },
    ],
  },
];
